"""modified post comment table

Revision ID: 55188fcbd7ca
Revises: a2b1a53b1b96
Create Date: 2022-07-14 00:13:16.127138

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '55188fcbd7ca'
down_revision = 'a2b1a53b1b96'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'author', ['name'])
    op.create_unique_constraint('author_keyword_unique', 'author_keyword', ['author_id', 'keyword_id'])
    op.add_column('comment', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('post', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('post', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('post', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.drop_column('comment', 'updated_at')
    op.drop_constraint('author_keyword_unique', 'author_keyword', type_='unique')
    op.drop_constraint(None, 'author', type_='unique')
    # ### end Alembic commands ###
