"""update post, comment table

Revision ID: a2b1a53b1b96
Revises: d2567d688c63
Create Date: 2022-07-13 01:42:21.981711

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a2b1a53b1b96'
down_revision = 'd2567d688c63'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('author_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comment', 'author', ['author_id'], ['id'])
    op.drop_column('comment', 'user_name')
    op.add_column('post', sa.Column('author_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'post', 'author', ['author_id'], ['id'])
    op.drop_column('post', 'user_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('user_name', mysql.VARCHAR(length=100), nullable=True))
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_column('post', 'author_id')
    op.add_column('comment', sa.Column('user_name', mysql.VARCHAR(length=100), nullable=False))
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_column('comment', 'author_id')
    # ### end Alembic commands ###
